insert into customer (id, name) values (1001, 'Starlight Cinema');
insert into customer (id, name) values (1002, 'Moonbean Theater');
insert into customer (id, name) values (1003, 'Sunset Playhouse');
insert into customer (id, name) values (1004, 'Silver Screen Theater');
insert into customer (id, name) values (1005, 'Golden Gate Theater');
insert into customer (id, name) values (1006, 'Emerald City Playhouse');
insert into customer (id, name) values (1007, 'Ruby Red Cinema');
insert into customer (id, name) values (1008, 'Saphire Stage');
insert into customer (id, name) values (1009, 'Diamond Theater');
insert into customer (id, name) values (1010, 'Platinum Playhouse');
insert into customer (id, name) values (1011, 'Crystal Clear Cinema');
insert into customer (id, name) values (1012, 'Amber Avenue Theater');
insert into customer (id, name) values (1013, 'Ivory Towe Playhouse');
insert into customer (id, name) values (1014, 'Crimson Curtain Theater');
insert into customer (id, name) values (1015, 'Azure Sky Cinema');
insert into customer (id, name) values (1016, 'Opal Opera House');
insert into customer (id, name) values (1017, 'Topaz Terrace Theater');
insert into customer (id, name) values (1018, 'Jade Jewel Playhouse');
insert into customer (id, name) values (1019, 'Pearl Palace');
insert into customer (id, name) values (1020, 'Onyx Opera');
insert into customer (id, name) values (1021, 'Cobalt Cove Cinema');
insert into customer (id, name) values (1022, 'Magenta Moon Theater');
insert into customer (id, name) values (1023, 'Violet Vista Playhouse');
insert into customer (id, name) values (1024, 'Bronce Bill Theater');
insert into customer (id, name) values (1025, 'Copper Creek Cinema');

