insert into play (id, code, name, type_id) values (203, 'Many Rivers to Cross', 'Shanghai Express', 1);
insert into play (id, code, name, type_id) values (204, 'Minuscule: Valley of the Lost Ants (Minuscule - La vallée des fourmis perdues)', 'Secret Agent, The', 2);
insert into play (id, code, name, type_id) values (205, 'Floating Clouds  (Ukigumo)', 'Cast a Dark Shadow (Angel)', 3);
insert into play (id, code, name, type_id) values (206, 'House II: The Second Story', 'Whose Life Is It Anyway?', 4);
insert into play (id, code, name, type_id) values (207, 'Essential Killing', '2-Headed Shark Attack', 5);
insert into play (id, code, name, type_id) values (208, 'Rainbow Valley', 'Blot, The', 6);
insert into play (id, code, name, type_id) values (209, 'Cardcaptor Sakura: The Sealed Card', 'Project Nim', 7);
insert into play (id, code, name, type_id) values (210, 'Man Escaped, A (Un  condamné à mort s''est échappé ou Le vent souffle où il veut)', 'Where Is the Friend''s Home? (Where Is My Friend''s House?) (Khane-ye doust kodjast?)', 8);
insert into play (id, code, name, type_id) values (211, 'Eye for an Eye, An (Silmä silmästä)', 'Female Agents (Les femmes de l''ombre)', 9);
insert into play (id, code, name, type_id) values (212, 'SS Camp 5: Women''s Hell (SS Lager 5: L''inferno delle donne)', 'Beat That My Heart Skipped, The (battre mon coeur s''est arrêté, De)', 10);
insert into play (id, code, name, type_id) values (213, 'Labor Day', 'Chronicle of a Summer (Chronique d''un été)', 11);
insert into play (id, code, name, type_id) values (214, 'Great Magician, The (Daai mo seut si)', 'Robin Williams: Weapons of Self Destruction', 12);
insert into play (id, code, name, type_id) values (215, 'Rory O''Shea Was Here (Inside I''m Dancing)', 'Escapist, The', 13);
insert into play (id, code, name, type_id) values (216, 'Computer Chess', 'Godfather: Part III, The', 14);
insert into play (id, code, name, type_id) values (217, 'Lilies of the Field', 'Dark Backward, The', 15);
insert into play (id, code, name, type_id) values (218, 'East of Eden', 'Into the Arms of Strangers: Stories of the Kindertransport', 16);
insert into play (id, code, name, type_id) values (219, 'My Wife is an Actress (Ma Femme est une Actrice)', 'McCabe & Mrs. Miller', 17);
insert into play (id, code, name, type_id) values (220, 'Best Defense', 'Omagh', 18);
insert into play (id, code, name, type_id) values (221, 'Forbidden Planet', 'Autobiography of Nicolae Ceausescu, The (Autobiografia lui Nicolae Ceausescu)', 19);
insert into play (id, code, name, type_id) values (222, 'Baby-Sitters Club, The', 'An Empress and the Warriors', 20);
insert into play (id, code, name, type_id) values (223, 'Ernest Goes to Jail', 'Four Weddings and a Funeral', 21);
insert into play (id, code, name, type_id) values (224, 'Blood of Heroes, The (Salute of the Jugger, The)', 'All the Fine Young Cannibals', 22);
insert into play (id, code, name, type_id) values (225, '10 minutes (10 minuta)', 'Conquest of Space', 23);
insert into play (id, code, name, type_id) values (226, 'Last Command, The', 'Tora-san''s Love Call (Otoko wa tsurai yo: Torajiro koiuta)', 24);
insert into play (id, code, name, type_id) values (227, 'Hotel de Love', 'Capricious Summer (Rozmarné léto)', 25);
insert into play (id, code, name, type_id) values (228, 'Phantom of the Opera', 'Vehicle 19', 26);
insert into play (id, code, name, type_id) values (229, 'Get on Up', 'Shout, The', 27);
insert into play (id, code, name, type_id) values (230, 'Enemies of Reason, The', 'Satan''s Brew (Satansbraten)', 28);
insert into play (id, code, name, type_id) values (231, 'Nömadak TX', 'Pirates of Penzance, The', 29);
insert into play (id, code, name, type_id) values (232, 'Bed of Roses', 'InAPPropriate Comedy', 30);
insert into play (id, code, name, type_id) values (233, 'Dracula Untold', 'With a Friend Like Harry... (Harry, un ami qui vous veut du bien)', 31);
insert into play (id, code, name, type_id) values (234, 'Prizzi''s Honor', 'Legend of the Boneknapper Dragon', 32);
insert into play (id, code, name, type_id) values (235, 'Floating Skyscrapers', 'Beginning of an Unknown Era (Nachalo nevedomogo veka)', 33);
insert into play (id, code, name, type_id) values (236, 'Don''t Go in the House', 'Spinning Boris', 34);
insert into play (id, code, name, type_id) values (237, 'State of Siege (État de siège)', 'Manchurian Candidate, The', 35);
insert into play (id, code, name, type_id) values (238, 'Call Her Savage', 'Red Shoes, The (Bunhongsin)', 36);
insert into play (id, code, name, type_id) values (239, 'From Beyond', 'Sugar & Spice', 37);
insert into play (id, code, name, type_id) values (240, 'Class Reunion', 'Odd Life of Timothy Green, The', 38);
insert into play (id, code, name, type_id) values (241, 'Stray Cat Rock: Sex Hunter (Nora-neko rokku: Sekkusu hanta)', 'War Horse', 39);
insert into play (id, code, name, type_id) values (242, 'HE Who Gets Slapped', 'Zombie (a.k.a. Zombie 2: The Dead Are Among Us) (Zombi 2)', 40);
insert into play (id, code, name, type_id) values (243, 'Lara Croft: Tomb Raider', 'Himalaya (Himalaya - l''enfance d''un chef)', 41);
insert into play (id, code, name, type_id) values (244, 'Bone Man, The (Der Knochenmann)', 'Period of Adjustment', 42);
insert into play (id, code, name, type_id) values (245, 'Coup de grâce (Der Fangschuß)', 'Screamers', 43);
insert into play (id, code, name, type_id) values (246, 'National Lampoon''s Vacation', 'Conspiracy, The', 44);
insert into play (id, code, name, type_id) values (247, 'Hitler''s Stealth Fighter', 'Me and You and Everyone We Know', 45);
insert into play (id, code, name, type_id) values (248, 'Matchmaker, The', 'Freeze Frame', 46);
insert into play (id, code, name, type_id) values (249, 'Evangelion: 3.0 You Can (Not) Redo', 'Cat People', 47);
insert into play (id, code, name, type_id) values (250, 'Cold Steel', 'The Trans-Atlantic Mystery', 48);
insert into play (id, code, name, type_id) values (251, 'Red-Headed Woman', 'Body Count', 49);
insert into play (id, code, name, type_id) values (252, 'Banana Joe', 'Evil Dead', 50);
insert into play (id, code, name, type_id) values (253, 'Fatal Hour, The', 'Breaks, The', 51);
insert into play (id, code, name, type_id) values (254, 'Tokyo Story (Tôkyô monogatari)', 'Frozen Dead, The', 52);
insert into play (id, code, name, type_id) values (255, 'Songcatcher', 'The Baby Maker', 53);
insert into play (id, code, name, type_id) values (256, 'The Chumscrubber', '100 Years at the Movies', 54);
insert into play (id, code, name, type_id) values (257, 'Midnight Crossing', 'The UFO Incident', 55);
insert into play (id, code, name, type_id) values (258, 'Great Beauty, The (Grande Bellezza, La)', 'August (Elokuu) ', 56);
insert into play (id, code, name, type_id) values (259, 'Slumdog Millionaire', 'Between Strangers', 57);
insert into play (id, code, name, type_id) values (260, 'Dirty Money (Un flic)', 'Junior Prom', 58);
insert into play (id, code, name, type_id) values (261, 'Two Deaths', 'Get Carter', 59);
insert into play (id, code, name, type_id) values (262, 'Broadway Rhythm', 'Garbage Pail Kids Movie, The', 60);
insert into play (id, code, name, type_id) values (263, 'Fall of the House of Usher, The (House of Usher)', 'Story of Maths, The', 61);
insert into play (id, code, name, type_id) values (264, 'Mrs. Parker and the Vicious Circle', 'Tar', 62);
insert into play (id, code, name, type_id) values (265, 'Assassination Bureau, The', 'Camera Obscura', 63);
insert into play (id, code, name, type_id) values (266, 'Adios Carmen', 'The Hire: Powder Keg', 64);
insert into play (id, code, name, type_id) values (267, 'She Wore a Yellow Ribbon', 'Jack the Giant Slayer', 65);
insert into play (id, code, name, type_id) values (268, 'Parisienne, La (Une parisienne)', 'Excalibur', 66);
insert into play (id, code, name, type_id) values (269, 'Last Ferry, The (Ostatni prom)', 'How to Lose a Guy in 10 Days', 67);
insert into play (id, code, name, type_id) values (270, 'Big Fan', 'Semi-Tough', 68);
insert into play (id, code, name, type_id) values (271, 'Wyrmwood', 'Hunter Prey', 69);
insert into play (id, code, name, type_id) values (272, 'Shoot to Kill', 'Love and Honor', 70);
insert into play (id, code, name, type_id) values (273, 'George of the Jungle', 'Hercules and the Circle of Fire', 71);
insert into play (id, code, name, type_id) values (274, 'So Evil, So Young', 'Dear Heart', 72);
insert into play (id, code, name, type_id) values (275, 'Route Irish', 'Australian Atomic Confessions', 73);
insert into play (id, code, name, type_id) values (276, 'Random Hearts', 'Dark Victory', 74);
insert into play (id, code, name, type_id) values (277, 'Fletch Lives', 'Rocket Singh: Salesman of the Year', 75);
insert into play (id, code, name, type_id) values (278, 'Final Destination 2', 'Assassination Tango', 76);
insert into play (id, code, name, type_id) values (279, 'Making Plans for Lena (Non ma fille, tu n''iras pas danser)', 'Day in the Life, A', 77);
insert into play (id, code, name, type_id) values (280, '3 Idiots', 'The Good Son', 78);
insert into play (id, code, name, type_id) values (281, 'May Fools (Milou en mai)', 'Italian Job, The', 79);
insert into play (id, code, name, type_id) values (282, 'Delhi-6', 'Vanquished, The (I vinti)', 80);
insert into play (id, code, name, type_id) values (283, 'Dead in Tombstone', 'White Elephant', 81);
insert into play (id, code, name, type_id) values (284, 'Confess', 'Butley', 82);
insert into play (id, code, name, type_id) values (285, 'Dolphin Tale 2', 'Notorious', 83);
insert into play (id, code, name, type_id) values (286, 'Santa''s Apprentice', 'The Old Gun', 84);
insert into play (id, code, name, type_id) values (287, 'Posto, Il', 'True Blue ', 85);
insert into play (id, code, name, type_id) values (288, 'Office Killer', 'Ugly', 86);
insert into play (id, code, name, type_id) values (289, 'Two Shots Fired', 'Letters to Juliet', 87);
insert into play (id, code, name, type_id) values (290, 'My Beautiful Dacia (Dacia, dragostea mea)', 'Happening, The', 88);
insert into play (id, code, name, type_id) values (291, 'Numbers Station, The', 'Boondock Saints II: All Saints Day, The', 89);
insert into play (id, code, name, type_id) values (292, 'Battle of Britain', 'Vic+Flo Saw a Bear', 90);
insert into play (id, code, name, type_id) values (293, 'The Clowns', 'Sorrow and the Pity, The (Le chagrin et la pitié)', 91);
insert into play (id, code, name, type_id) values (294, 'Beastly', 'Shanghai Noon', 92);
insert into play (id, code, name, type_id) values (295, 'Man Next Door, The (El hombre de al lado)', 'Better Luck Tomorrow', 93);
insert into play (id, code, name, type_id) values (296, 'Cheers for Miss Bishop', 'Career Opportunities', 94);
insert into play (id, code, name, type_id) values (297, 'Flamingo Road', 'Romance on the High Seas', 95);
insert into play (id, code, name, type_id) values (298, 'Simon Says', 'Diary of a Wimpy Kid: Dog Days', 96);
insert into play (id, code, name, type_id) values (299, 'Accidental Golfer, The (Den ofrivillige golfaren)', 'Out in the Dark', 97);
insert into play (id, code, name, type_id) values (300, 'Dry Summer (Susuz yaz) (Reflections)', 'Michael Jackson''s This Is It', 98);
insert into play (id, code, name, type_id) values (301, 'Missing, The', 'Company of Heroes', 99);
insert into play (id, code, name, type_id) values (302, 'Things Change', 'Ladybug Ladybug ', 100);
